module Rubarb
  CLIENT_VERSION = 63
  MIN_SERVER_VERSION = 38
  MIN_SERVER_VERSION_TIME = 20
  MIN_SERVER_VERSION_CLIENT_ID = 3
  MIN_SERVER_VERSION_LINKING = 70
  START_API = 71
  SEND_API_VERSION = 1
  EOL = "\0"
end